// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLpuCalSPLwmBrK5k2b8zQHieevJK19jg',
    appId: '1:30016596493:web:61fd700e506ee00c768344',
    messagingSenderId: '30016596493',
    projectId: 'okami-4bdff',
    authDomain: 'okami-4bdff.firebaseapp.com',
    storageBucket: 'okami-4bdff.firebasestorage.app',
    measurementId: 'G-0TCXMX1WXV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlqFuKCe09cd6Q39bLmfG5G4zZ5UdxYDE',
    appId: '1:30016596493:android:2a4f3f7ee7adc5eb768344',
    messagingSenderId: '30016596493',
    projectId: 'okami-4bdff',
    storageBucket: 'okami-4bdff.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBERrL5UOHXtzJUJ1LnhpJ6h0IEBKKMaws',
    appId: '1:30016596493:ios:2694077b0569e47e768344',
    messagingSenderId: '30016596493',
    projectId: 'okami-4bdff',
    storageBucket: 'okami-4bdff.firebasestorage.app',
    iosBundleId: 'com.example.okami',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBERrL5UOHXtzJUJ1LnhpJ6h0IEBKKMaws',
    appId: '1:30016596493:ios:2694077b0569e47e768344',
    messagingSenderId: '30016596493',
    projectId: 'okami-4bdff',
    storageBucket: 'okami-4bdff.firebasestorage.app',
    iosBundleId: 'com.example.okami',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLpuCalSPLwmBrK5k2b8zQHieevJK19jg',
    appId: '1:30016596493:web:e5f9a024e3f93375768344',
    messagingSenderId: '30016596493',
    projectId: 'okami-4bdff',
    authDomain: 'okami-4bdff.firebaseapp.com',
    storageBucket: 'okami-4bdff.firebasestorage.app',
    measurementId: 'G-18L1JQW51T',
  );
}
